###

POST https://proto-ai-buddy-backend.onrender.com/api/test
Content-Type: application/json

{
  "passcode": "1234"
}

###


GET https://proto-ai-buddy-backend.onrender.com/api/ping
Content-Type: application/json

{

}
